CREATE TABLE "new_court_suggestions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"suggested_by" varchar(255) NOT NULL,
	"suggested_by_user_name" varchar(255) NOT NULL,
	"status" varchar(50) DEFAULT 'pending' NOT NULL,
	"reviewed_by" varchar(255),
	"reviewed_by_user_name" varchar(255),
	"review_note" varchar(500),
	"reviewed_at" timestamp,
	"name" varchar(255) NOT NULL,
	"address" varchar(255) NOT NULL,
	"city" varchar(100) NOT NULL,
	"state" varchar(50) NOT NULL,
	"zip" varchar(20) NOT NULL,
	"latitude" numeric(10, 8),
	"longitude" numeric(11, 8),
	"court_type" varchar(50),
	"number_of_courts" integer,
	"surface" varchar(50),
	"court_condition" varchar(50),
	"hitting_wall" boolean,
	"lighted" boolean,
	"membership_required" boolean,
	"parking" boolean,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
